---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/**/*
    - vendor/**/*

Style/OpenStructUse:
  Enabled: false

Performance/MethodObjectAsBlock:
  Enabled: false
