# The book's title. Will be used everywhere!
title: "Testing Kitabu"

# The book's language.
language: "pt-BR"

# Your book copyright info.
# Here's some examples:
#
#   Copyright 2010 by John Doe.
#   Copyright 2010 by John Doe. This work is licensed under MIT License.
#   This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.
#
copyright: "Copyright (C) 2010 John Doe."

# Who's publishing this book.
publisher: "John Doe"

# When this book was published.
published_at: "2010-12-19"

# Some book description.
subject: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# Some keywords that identify this book.
keywords: "demo, book, pdf, epub, kitabu, textile, html, markdown"

# Some unique identification. Works great with your domain
# like `http://yourbook.example.com`.
uid: "MFXx9nj7uz"

# Your book identification like ISBN or ISSN.
identifier:
  id: "http://kitabu.example.com.br"
  type: "URL" # can be ISBN, ISSN or URL

# This book's authors.
authors:
  - "John Doe"
  - "Mary Doe"

# The base URL from your source code.
base_url: http://example.com

# You can rename your text structure automatically.
# All you have to do is using a list will all your chapters and
# then you can run `kitabu rearrange`.
structure:
  - Markdown_Chapter.markdown
  - Textile_Chapter.textile
  - HTML_Chapter.html
  - With_Directory
    - Some_Chapter.mkdn
