---
# The book's title. Will be used everywhere!
title: "Testing Kitabu"

# The book's subtitle. Optional.
subtitle: ""

# The book's language.
language: "pt-BR"

# Your book copyright info.
# Here's some examples:
#
#   Copyright 2010 by John Doe.
#   Copyright 2010 by John Doe. This work is licensed under MIT License.
#   This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.
#
copyright: "Copyright (C) 2010 John Doe."

# Who's publishing this book.
publisher: "John Doe"

# When this book was published.
published_at: "2010-12-19"

# Some book description.
subject:
  "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua."

# Some keywords that identify this book.
keywords: "demo, book, pdf, epub, kitabu, textile, html, markdown"

# Some unique identification. Works great with your domain
# like `yourbook.example.com`.
uid: "MFXx9nj7uz"

# Your book identification like ISBN or ISSN.
identifiers: []

# This book's authors.
creators:
  - "John Doe"
  - "Mary Doe"

# This book's contributors.
contributors: []

# Syntax highlight theme. Can be any of supported by Rouge.
syntax_highlight_theme: github

# Accent color. This will be set as a CSS variable, so you can use it on all
# CSS files like `color: var(--accent-color)`.
css_accent_color: "#5091b1"
