# The book's title. Will be used everywhere!
title: "Rails Guides: Getting Started"

# The book's language.
language: en

# Your book copyright info.
# Here's some examples:
#
#   Copyright 2010 by Nando Vieira.
#   Copyright 2010 by Nando Vieira. This work is licensed under MIT License.
#   This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.
#
copyright: "Copyright (C) 2010 Rails Documentation Team."

# Who's publishing this book.
publisher: "Nando Vieira"

# When this book was published.
published_at: "2010-12-19"

# Some book description.
subject: "These guides are designed to make you immediately productive with Rails, and to help you understand how all of the pieces fit together."

# Some keywords that identify this book.
keywords: "Ruby on Rails, Ruby, MVC, Getting Started, PDF, HOWTO, Web Development, Framework"

# Some unique identification. Works great with your domain
# like `http://yourbook.example.com`.
uid: "b731cad288c08e875982ebc3d30f9b2d"

# Your book identification like ISBN or ISSN.
identifier:
  id: "http://yourbook.example.com"
  type: "URL" # can be ISBN, ISSN or URL

# This book authors.
authors:
  - "Rails Documentation Team"

# The base URL from your source code.
base_url: http://example.com
